src/objects/AM_Asset__c.object
<CustomObject>
    <label>New Asset</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agile Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AM_Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Asset associated with this case</description>
        <label>AM_Asset</label>
        <referenceTo>AM_Asset__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Service_Request__c.object
<CustomObject>
    <description>This objects is to store data for out of service records</description>
    <fields>
        <fullName>AM_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Lookup field stores Asset detail</description>
        <inlineHelpText>It shows Asset detail</inlineHelpText>
        <label>AM_Asset</label>
        <referenceTo>AM_Asset__c</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>This field is to store Service Request description</description>
        <inlineHelpText>It shows Service Request description</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mark_Asset_as_out_of_service__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checking this box will fire a trigger that will set the &quot;Out of service&quot; checkbox on the corresponding asset as True.</description>
        <inlineHelpText>it shows Asset status as Out Of Service</inlineHelpText>
        <label>Mark Asset as out of service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>It stores subject of service request</description>
        <inlineHelpText>It Shows Subject of Service Request</inlineHelpText>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CAM_CaseController_Test.cls
/* Description: Test class for the AM_CaseController */
@isTest
private class CAM_CaseController_Test {
    
    @isTest static void testCaseController1() {
        List<AM_Asset__c> assets = CAM_TestUtilities.createTestAssets(1);
        ApexPages.StandardController sc = new ApexPages.StandardController(assets[0]);
        CAM_CaseController con = new CAM_CaseController(sc);
        
        PageReference casePage = Page.CAM_CasePage;
        Test.setCurrentPage(casePage);
        
        con.assetName='test';
        System.assertEquals(con.assetName, 'test');
		//con.asset= 'Chair';
		con.attachmentName='test';
        System.assertEquals(con.attachmentName,'test');
        
        
        
        
        //Subject is empty
        con.createCase();
        System.assert(con.errormessages.size()>0);

        con.aCase.Subject__c = 'TestSubject';
        
        //Asset is empty
        con.aCase.AM_Asset__c = null;
        con.createCase();
        System.assert(con.errormessages.size()>0);
        
          con.aCase.AM_Asset__c = con.asset.id;
       //   con.aCase.AM_Asset__c= 'a0755000005IoU7';
        /* Ankita Code */
       // List<AM_Asset__c> TestAsset = new List<AM_Asset__c>{ }
         
        //Description is empty
        con.createCase();
        System.assert(ApexPages.hasMessages());
                
        con.aCase.Description__c = 'TestDescription';
        con.aCase.Mark_Asset_as_out_of_service__c = false;
        
        con.attach.body = Blob.valueOf('Unit Test Attachment Body');
        con.attach.Name = 'Test file name'; 
      
        con.createCase();
        
        Service_Request__c c = [select id, Subject__c from Service_Request__c where id =: con.newCaseId limit 1];
        Attachment a = [select id, Name from Attachment where parentId =: c.Id];
        System.AssertEquals(c.Subject__c, 'TestSubject');
        System.AssertEquals(a.Name, 'Test file name');
        System.assert(!con.showLookUp);
        
        //Try creating case with the same case ID
        con.aCase.Id = con.newCaseId;
        con.aCase.AM_Asset__c = assets[0].Id;
        con.aCase.Subject__c = 'TestSubject';
        con.aCase.Description__c = 'TestDescription';
                
        con.createCase(); 
        System.assert(ApexPages.hasMessages());
     
        System.assert(!con.showConfirmation);   
        
        con.backMethod();
        con.closeConfirmation();
        
        
    }
    
    @isTest static void testCaseController2() {
        List<Contact> contacts = CAM_TestUtilities.createTestContacts(1);

        ApexPages.StandardController sc = new ApexPages.StandardController(contacts[0]);
        CAM_CaseController con = new CAM_CaseController(sc);
        System.assert(ApexPages.hasMessages());       
 
    }

    @isTest static void testNoAttachment() {
        List<AM_Asset__c> assets = CAM_TestUtilities.createTestAssets(1);

        ApexPages.StandardController sc = new ApexPages.StandardController(assets[0]);
        CAM_CaseController con = new CAM_CaseController(sc);
        
        PageReference casePage = Page.CAM_CasePage;
        Test.setCurrentPage(casePage);
        
        con.aCase.Subject__c = 'TestSubject';     
        con.aCase.Description__c = 'TestDescription';
        con.aCase.Mark_Asset_as_out_of_service__c = false;
        
        con.createCase();
        
        Service_Request__c c = [select id, Subject__c from Service_Request__c where id =: con.newCaseId limit 1];
        System.AssertEquals(c.Subject__c, 'TestSubject');
        System.assert(con.showConfirmation);
        
        
        
        
    }            
}