src/objects/AM_Asset__c.object
<CustomObject>
    <label>New Asset</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agile Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AM_Asset_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>AM_Asset__c</fullName>
        <description>It is Lookup field connected with Asset Object</description>
        <inlineHelpText>Select Asset</inlineHelpText>
        <label>Asset</label>
        <referenceTo>AM_Asset__c</referenceTo>
        <relationshipLabel>Asset Allocations</relationshipLabel>
        <relationshipName>Asset_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AM_End_Date__c</fullName>
        <description>This Date is for Ending of Allocate</description>
        <inlineHelpText>Select Date when u want to End Allocation</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>AM_Start_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>This Date is for Starting of Allocate</description>
        <inlineHelpText>Select Date when u want to Start Allocation</inlineHelpText>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Asset Allocation</label>
    <nameField>
        <displayFormat>AL-{00000000}</displayFormat>
        <label>Asset Alocation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Allocate</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CAM_ValidateDates_Test.cls
/*    Test class for the CAM_ValidateDates_AllocationTrigger */

@isTest
private class CAM_ValidateDates_Test {
    
    @isTest static void test_method_one() {
        CAM_TestUtilities.createTestAllocations();
        List<AM_Asset_Allocation__c> allocList = new List<AM_Asset_Allocation__c>();
        allocList.add(new AM_Asset_Allocation__c(AM_Asset__c = CAM_TestUtilities.asset.Id, AM_start_date__c = Date.Today(), AM_end_date__c = Date.Today()+1));
        try {
            insert allocList;
        } catch (DmlException ex) {
            System.assert(ex.getTypeName().contains('Dml'));
        }   
        
        
       
    }
    
}