src/objects/AM_Asset__c.object
<CustomObject>
    <fields>
        <fullName>AM_ID__c</fullName>
        <description>External ID for the asset</description>
        <externalId>true</externalId>
        <inlineHelpText>External ID for the asset</inlineHelpText>
        <label>Model No.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>New Asset</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agile Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AM_Asset_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>AM_Asset__c</fullName>
        <description>It is Lookup field connected with Asset Object</description>
        <inlineHelpText>Select Asset</inlineHelpText>
        <label>Asset</label>
        <referenceTo>AM_Asset__c</referenceTo>
        <relationshipLabel>Asset Allocations</relationshipLabel>
        <relationshipName>Asset_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AM_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is to store contact for allocation</description>
        <inlineHelpText>Select Contact to whom you want to allocate Asset</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Asset Allocations</relationshipLabel>
        <relationshipName>Asset_Allocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AM_End_Date__c</fullName>
        <description>This Date is for Ending of Allocate</description>
        <inlineHelpText>Select Date when u want to End Allocation</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>AM_Start_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>This Date is for Starting of Allocate</description>
        <inlineHelpText>Select Date when u want to Start Allocation</inlineHelpText>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Asset Allocation</label>
    <nameField>
        <displayFormat>AL-{00000000}</displayFormat>
        <label>Asset Alocation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Allocate</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Request__c.object
<CustomObject>
    <description>This objects is to store data for out of service records</description>
    <fields>
        <fullName>AM_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Lookup field stores Asset detail</description>
        <inlineHelpText>It shows Asset detail</inlineHelpText>
        <label>AM_Asset</label>
        <referenceTo>AM_Asset__c</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mark_Asset_as_out_of_service__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checking this box will fire a trigger that will set the &quot;Out of service&quot; checkbox on the corresponding asset as True.</description>
        <inlineHelpText>it shows Asset status as Out Of Service</inlineHelpText>
        <label>Mark Asset as out of service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>It stores subject of service request</description>
        <inlineHelpText>It Shows Subject of Service Request</inlineHelpText>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CAM_TestUtilities.cls
/*   Utility test class to generate test data  */


@isTest
public class CAM_TestUtilities {

    //Assets
    public static List<AM_Asset__c> createTestAssets(Integer numAssets) {
        //Recordtypes
        List<RecordType> rtList= [select Id, 
                                         DeveloperName,
                                         Name 
                                  from RecordType
                                  where sObjectType =: CAM_Constants.AM_ASSET_API_NAME];                         

        List<AM_Asset__c> assetList = new List<AM_Asset__c>();
        for (Integer i=0; i<numAssets; i++) {
            assetList.add(new AM_Asset__c(AM_ID__c='TestAsset' + i, RecordTypeId = rtList[0].Id));
        }
        
        //insert assetList;
        //return assetList;
        try{
        insert assetList;
        }catch(DMLException e)
        {
            e.getMessage();
        }
           
        return assetList;
        
    } 

    //Contacts
    public static List<Contact> createTestContacts(Integer numContacts) {
        List<Contact> contactList = new List<Contact>();
        Account a = new Account(Name='TestAccount');
        insert a;
        for(Integer j=0;j<numContacts;j++) {
            contactList.add(new Contact(firstname='Test'+j,lastname='Test'+j,AccountId=a.Id));
        }
        insert contactList;     
        return contactList;
    }

    //Cases
    public static List<Service_Request__c> createTestCases(Integer numCases, AM_Asset__c asset) {
        List<Service_Request__c> cases = new List<Service_Request__c>();
        for (Integer i=0; i<numCases; i++) {
            cases.add(new Service_Request__c(AM_Asset__c=asset.Id, Mark_Asset_as_out_of_service__c=true, Subject__c='TestCase'+i));
        }
      //  insert cases;
      //  return cases;
        
        try{
        insert cases;
        }catch(DMLException e)
        {
            e.getMessage();
        }
           
        return cases;
    }

    //Allocations List
    public static List<AM_Asset_Allocation__c> createTestAllocations() {
        List<Contact> conList = createTestContacts(1);
        asset = new AM_Asset__c();
        //insert asset;
        try{
            insert asset;
        }catch(DMLException e)
        {e.getMessage();
        }

        List<AM_Asset_Allocation__c> allocList = new List<AM_Asset_Allocation__c>();
        allocList.add(new AM_Asset_Allocation__c(AM_Start_date__c = Date.today(), AM_End_date__c = Date.today() + 5, AM_Asset__c = asset.Id, AM_Contact__c = conList[0].Id));
      //  insert allocList;
      //  return allocList;
        
        try{
        insert allocList;
        }catch(DMLException e)
        {
            e.getMessage();
        }
           
        return allocList;
    }

    //Single Allocation
    public static AM_Asset_Allocation__c createTestAllocation(AM_Asset__c asset) {
        List<Contact> conList = createTestContacts(1);

        AM_Asset_Allocation__c newAlloc = new AM_Asset_Allocation__c(AM_Start_date__c = Date.today(), AM_End_date__c = Date.today() + 5, AM_Asset__c = asset.Id, AM_Contact__c = conList[0].Id);
        // insert newAlloc;
       // return newAlloc;
       try{
        insert newAlloc;
        }catch(DMLException e)
        {
            e.getMessage();
        }
           
        return newAlloc;
    }    
    
    public static AM_Asset__c asset {
        get; private set;
    }

    //Test User
    public static User createTestUser() {

         Profile p = [select id from profile where name='Standard User']; 

         User newUser = new User(alias = 'auser', 
                           email='assetuser@assetapp.com', 
                           emailencodingkey='UTF-8', 
                           lastname='Testing', 
                           languagelocalekey='en_US', 
                           localesidkey='en_US', 
                           profileid = p.Id, 
                           timezonesidkey='America/Los_Angeles',
                           username='assetuser@assetapp.com');

         insert newUser;
         return newUser;
    }

    //Method to check if a message exists
    public static Boolean checkMessageExists(List<ApexPages.Message> msgs, String msgText)
    {
        Boolean messageExists = false;
        for(Apexpages.Message msg:msgs){
            if (msg.getDetail().contains(msgText))
            {
                messageExists = true;
                break;
            } 
        }
        return messageExists;            
    }
    
    static testmethod void test1() {
        List<AM_Asset__c> assets = CAM_TestUtilities.createTestAssets(3);
        CAM_TestUtilities.createTestContacts(3);
        CAM_TestUtilities.createTestCases(3, assets[0]);    
        CAM_TestUtilities.createTestAllocations();    
    }
}