src/objects/AM_Asset__c.object
<CustomObject>
    <fields>
        <fullName>AM_Out_of_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is for Asset status which shows Out Of Service</description>
        <inlineHelpText>This checkbox is for Asset status which shows Out Of Service</inlineHelpText>
        <label>Out of Service</label>
        <type>Checkbox</type>
    </fields>
    <label>New Asset</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agile Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AM_Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Asset associated with this case</description>
        <label>AM_Asset</label>
        <referenceTo>AM_Asset__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AM_Mark_Asset_as_out_of_service__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checking this box will fire a trigger that will set the &quot;Out of service&quot; checkbox on the corresponding asset as True.</description>
        <label>Mark Asset as out of service</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/CAM_SetAssetOOS_Test.cls
/* Description: Test class for AM_SetAssetOOS_CaseTrigger */

@isTest
private class CAM_SetAssetOOS_Test {
    
  /*  @isTest static void testTrigger() {
        List<AM_Asset__c> assets = CAM_TestUtilities.createTestAssets(1);
        List<Case> cases = CAM_TestUtilities.createTestCases(1, assets[0]);
        Case aCase = cases[0];
        aCase.AM_Mark_Asset_as_out_of_service__c = true;
       // update aCase;
        try{
            update aCase;
        }catch(DMLException e)
        { e.getMessage();
        }
        
        AM_Asset__c myAsset = [select id, AM_Out_of_Service__c from AM_Asset__c where id =: aCase.AM_Asset__c];
        System.Assert(myAsset.AM_Out_of_service__c);
    } */
    
}