src/objects/AM_Asset__c.object
<CustomObject>
    <fields>
        <fullName>AM_Status__c</fullName>
        <description>Describes the status of an asset</description>
        <formula>IF( AM_Available_for_allocation__c , &quot;Available&quot;, (IF ( AM_Out_of_Service__c ,&quot;Out Of Service&quot;,&quot;Assigned&quot;)))</formula>
        <inlineHelpText>It shows status of an Asset</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>This field shows quantity of the asset items</description>
        <inlineHelpText>Enter Quantity of Asset</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>New Asset</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agile Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AM_Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Asset associated with this case</description>
        <label>AM_Asset</label>
        <referenceTo>AM_Asset__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>AM_Asset_Support</fullName>
        <active>true</active>
        <businessProcess>Asset Support Process</businessProcess>
        <label>Asset Support</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/CAM_Constants.cls
/* Description: This class contains all constants used in this app's Apex classes */

public with sharing class CAM_Constants {

    //AM_Asset AM_Status__c values
    public static final String AM_ASSET_STATUS_AVAILABLE = 'Available';
    public static final String AM_ASSET_STATUS_ASSIGNED = 'Assigned';
    public static final String AM_ASSET_STATUS_OUTOFSERVICE = 'OutofService';

    //Constant for AM_Asset__c object type
    public static final String AM_ASSET_API_NAME = 'AgileAssets__AM_Asset__c';

    //Constant for CONTACT object type
    public static final String AM_CONTACT_API_NAME = 'Contact';    

    //Constant for AM_Status__c field name
    public static final String AM_STATUS_API_NAME = 'AgileAssets__AM_Status__c';  
    
    //Constant for Quantity__c field name
    public static final String AM_QUANTITY_API_NAME = 'AgileAssets__Quantity__c';

    //Constant for Case Record Type Name
    public static final String AM_CASE_RT_NAME = 'AM_Asset_Support';  

    //Constant for Dynamic SOQL 
    //'Where'
    public static final String AM_WHERE = String.escapeSingleQuotes('where');
    //'Like'
    public static final String AM_LIKE = String.escapeSingleQuotes('Like');
    //'AND'
    public static final String AM_AND = String.escapeSingleQuotes('AND');
    //'OR'
    public static final String AM_OR = String.escapeSingleQuotes('OR');
    //'SPACE'
    public static final String AM_SPACE = String.escapeSingleQuotes(' ');
}