src/objects/Asset_Requested__c.object
<CustomObject>
    <description>This Object is used to store Asset Request Data</description>
    <fields>
        <fullName>Asset_Category__c</fullName>
        <description>This field is to store record type submitted by Asset Request field Asset Type</description>
        <inlineHelpText>It Shows Asset Category</inlineHelpText>
        <label>Asset Category</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asset_Type__c</fullName>
        <description>This field is to store the value of &apos;Asset Type&apos; of the VF page Asset Type</description>
        <inlineHelpText>It shows Asset Type</inlineHelpText>
        <label>Asset Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>This field is to Store Description from Asset Request Page</description>
        <inlineHelpText>It Shows Asset Description</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>This field is to store Quantity submitted by Asset Request page</description>
        <inlineHelpText>It Shows Quantity</inlineHelpText>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request_Date__c</fullName>
        <description>This field is to store Date for Asset Request</description>
        <inlineHelpText>It Shows Request Date</inlineHelpText>
        <label>Request Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Request_Name__c</fullName>
        <description>This field is to Store of the Subject of request</description>
        <inlineHelpText>It Shows Asset Request Name</inlineHelpText>
        <label>Request Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <description>This picklist is to store &apos;Type of Request&apos; field from Asset Request VF Page</description>
        <inlineHelpText>It Shows Request Type</inlineHelpText>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service/Repair</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Asset Requested</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Asset Requested Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Requested</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CAM_Request_Page.cls
Public class CAM_Request_Page{
    
    public Attachment getAttachedFile(){
    attachedFile = New Attachment();
    return attachedFile;
    }
    public Attachment attachedFile;
    public String RequestName {get; set;}
    public String btype {get; set;}
    public String stage {get; set;}
    public String stagedata {get; set;}
    public integer quantity{get;set;}
  
 
    public String description {get; set;}
    public String Filename {get; set;}
    

     public Date requestDate = date.today();
    
     ID currentID;
    List<Asset_Requested__c> listAssetRequest = new List<Asset_Requested__c>();
 
    public CAM_Request_Page(){
    getTypes();
    getStages();
    getStagesdata();
    }  
    public List<SelectOption> getTypes()
    {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('--None','--None--'));
        options.add(new SelectOption('Purchase','Purchase'));
        options.add(new SelectOption('Allocation','Allocation'));
        options.add(new SelectOption('Service/Repair','Service/Repair'));
        return options;
    }
    public List<SelectOption> getStages()
    {
        List<RecordType> rtList= [select  Name,DeveloperName
                                          from RecordType
                                          where sObjectType =: CAM_Constants.AM_ASSET_API_NAME];  

        List<SelectOption> options=new List<SelectOption>();
       
        options.add(new SelectOption('--None','--None'));
        for (RecordType rt : rtList) 
            {
                //Populate SelectList
                options.add(new SelectOption(rt.Name, rt.Name));
             
            }
        return options; 
        
    
        
    } 
     public List<SelectOption> getStagesdata()
    {
      
        
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('--None','--None--'));
        options.add(new SelectOption('Desktop/Laptop','Desktop/Laptop'));
        options.add(new SelectOption('Accessories','Accessories'));
        options.add(new SelectOption('Networking','Networking'));
        options.add(new SelectOption('General','General'));
        options.add(new SelectOption('Book','Book'));
        options.add(new SelectOption('Chromebook','Chromebook'));
        options.add(new SelectOption('Office Furniture','Office Furniture'));
        options.add(new SelectOption('Domestic Item','Domestic Item'));
        options.add(new SelectOption('CD/DVD','CD/DVD'));
        options.add(new SelectOption('Other','Other'));
        return options;
    } 

    public PageReference requestform() {


    Asset_Requested__c ar = new Asset_Requested__c();
    ar.Request_Name__c=RequestName;
    ar.Description__c=description;
    ar.Request_Type__c=btype;
    ar.Asset_Category__c=stage;
    ar.Asset_Type__c=stagedata;
    ar.Quantity__c=quantity;
    ar.Request_Date__c=requestDate;
 
        listAssetRequest.add(ar);
    
    if (listAssetRequest.isEmpty() == false) {
        Database.insert(listAssetRequest);
        for(Asset_Requested__c ars: listAssetRequest){
        system.debug(' ID of inserted request record'+ ars.Id);
        currentID = ars.Id;
        system.debug(' ID of currentID record'+ currentID);
         if(attachedFile.Name != Null)
         {   
            Attachment a = new Attachment(ParentId = ars.Id, name = attachedFile.Name, body = attachedFile.Body);
            insert a; }
        }
        
        RequestName = '';
        btype = '';
        stage  = '';
        stagedata = '';
        quantity=null; 
        description = '';
    }
    PageReference prf = new PageReference('/apex/CAM_RequestPage');
    prf.setRedirect(true);
    return prf;
 
    }
}