src/objects/LMA_Audit__c.object
<CustomObject>
    <description>Confident Governance - This object for LMA Audit purpose</description>
    <fields>
        <fullName>App_Name__c</fullName>
        <description>License assigned app name</description>
        <inlineHelpText>It Shows License assigned app name</inlineHelpText>
        <label>App_Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expire_Date__c</fullName>
        <description>it stores Expire Date for licence</description>
        <inlineHelpText>It shows Expire Date for Licence</inlineHelpText>
        <label>Expire_Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Show license status</description>
        <inlineHelpText>Show license status</inlineHelpText>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>LMA Audit</label>
    <nameField>
        <displayFormat>LMA-{0000}</displayFormat>
        <label>LMA_Audit No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LMA_Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/License_Key_TestClass.cls
@isTest(SeeAllData=True)
public class License_Key_TestClass {
    public static testmethod void matchLicenseKeys_TestMethod()
    {
        License_Key lk = new License_Key();
        string check = 'test';
     
        if(check !=null)
        {
            if(check == 'test')
                check = 'ok';
        }
        if(check == 'ok')
        {
         check = 'test';
         string currentapp='ConfidentG';
         string status = 'Active';
         List<object> lma = [select Status__c,App_Name__c,Expire_Date__c from LMA_Audit__c where App_Name__c =: currentapp LIMIT 1];
       
//        lk.matchLicenseKeys();                
        }else{
            
         check = 'tested';
         string currentapp='ConfidentG';
         string status = 'Active';
         List<object> lma = [select Status__c,App_Name__c,Expire_Date__c from LMA_Audit__c where App_Name__c =: currentapp LIMIT 1];
       
         lk.matchLicenseKeys();
        
        }
        try{
            check = 'test';
            lk.matchLicenseKeys();
        }
        catch(DmlException e)
        {
         check = 'tested';
         string currentapp='ConfidentG';
         string status = 'Active';
         List<object> lma = [select Status__c,App_Name__c,Expire_Date__c from LMA_Audit__c where App_Name__c =: currentapp LIMIT 1];
         lk.matchLicenseKeys(); 
        }
    }
     public static testmethod Pagereference TestmatchLicenseKeys()
     {
         License_Key cg = new License_Key();
 //        cg.Perpetual= true;
         cg.No_Of_Seats='test';
         cg.matchLicenseKeys='test1';
         cg.select_module='test2';
         cg.Perpetual=true;
         cg.Licensekey='test3';
         
         string surveyPrefix = '/apex/ClearGRCApps';
         Pagereference p = new PageReference(surveyPrefix);
      
         string currentapp='ConfidentG';
         string status = 'Active';
         List<object> lma = [select Status__c,App_Name__c,Expire_Date__c from LMA_Audit__c where App_Name__c =: currentapp LIMIT 1];
         cg.matchLicenseKeys();
         string str = 'test';
         System.assertEquals('test',str);
         return p; 
     }        
}