src/objects/LMA_Audit__c.object
<CustomObject>
    <description>Confident Governance - This object for LMA Audit purpose</description>
    <fields>
        <fullName>App_Name__c</fullName>
        <description>License assigned app name</description>
        <inlineHelpText>It Shows License assigned app name</inlineHelpText>
        <label>App_Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expire_Date__c</fullName>
        <description>it stores Expire Date for licence</description>
        <inlineHelpText>It shows Expire Date for Licence</inlineHelpText>
        <label>Expire_Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Show license status</description>
        <inlineHelpText>Show license status</inlineHelpText>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>LMA Audit</label>
    <nameField>
        <displayFormat>LMA-{0000}</displayFormat>
        <label>LMA_Audit No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LMA_Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_AssetsShowAllREcord.cls
@isTest(SeeAllData=True)
public class Test_AssetsShowAllREcord {
    static testMethod void test_redirectMilestone()
    {
         CAM_Assets_showAllRec cg = new CAM_Assets_showAllRec();
         string currentapp='Agile Assets';
         string status = 'Active';
   
        
         List<object> lma = [select Status__c,App_Name__c,Expire_Date__c from LMA_Audit__c where App_Name__c =: currentapp LIMIT 1];
       
         cg.getredirectAssets();
         cg.sendEmail();
        Boolean test1;
        Boolean test2;
        Boolean flag;
        Boolean  t1,t2,t3;
        
        if(test1==t1 & test2==t2)
        {
              flag = true;
        }
        
        try{
            
        }
        catch(DmlException e)
        {
           
          
        }
        
        string str = 'test';
        System.assertEquals('test',str);
    }


}