src/objects/LMA_Audit__c.object
<CustomObject>
    <description>Confident Governance - This object for LMA Audit purpose</description>
    <fields>
        <fullName>App_Name__c</fullName>
        <description>License assigned app name</description>
        <inlineHelpText>It Shows License assigned app name</inlineHelpText>
        <label>App_Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>it stores Contact</description>
        <inlineHelpText>Contact</inlineHelpText>
        <label>Contact</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Expire_Date__c</fullName>
        <description>it stores Expire Date for licence</description>
        <inlineHelpText>It shows Expire Date for Licence</inlineHelpText>
        <label>Expire_Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Install_Date__c</fullName>
        <description>It stores Install Date for Licenced Application</description>
        <inlineHelpText>It shows Install Date for Licenced Application</inlineHelpText>
        <label>Install_Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Key__c</fullName>
        <description>It stores Licence key</description>
        <inlineHelpText>It shows Licence key</inlineHelpText>
        <label>License_Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <description>It stores Licence Type</description>
        <inlineHelpText>It shows Licence Type</inlineHelpText>
        <label>License_Type</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Seats__c</fullName>
        <description>It stores Number of Licence</description>
        <inlineHelpText>It Shows Number of Licence</inlineHelpText>
        <label>No. of Seats</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Package_Version__c</fullName>
        <description>it stores Package version to which licence provided</description>
        <inlineHelpText>It shows Package Version</inlineHelpText>
        <label>Package_Version</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Show license status</description>
        <inlineHelpText>Show license status</inlineHelpText>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Org_Id__c</fullName>
        <label>Subscriber_Org_Id</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_ID__c</fullName>
        <label>User_ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LMA Audit</label>
    <nameField>
        <displayFormat>LMA-{0000}</displayFormat>
        <label>LMA_Audit No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LMA_Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/page_access__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Expire_date__c</fullName>
        <description>Store Expire date of License</description>
        <label>Expire date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Key__c</fullName>
        <label>License Key</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <description>For License Type</description>
        <label>License Type</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_ID__c</fullName>
        <label>User_ID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>page_access</label>
</CustomObject>

src/classes/SecureSettingsController_TestMethod.cls
@istest(SeeAllData=true)

public class SecureSettingsController_TestMethod
{
    
    static TestMethod void SecureSettingsController_TestMethod()
    {
    integer i;
        String Licensekey='test';
        String select_Lictype='EL';
    SecureSettingsController sc = new SecureSettingsController();
    sc.GenerateLicenseKeys();
        
    sc.LicInfo();
    sc.getLicenses();
    sc.LicenseType();
    sc.getobjNames();
    sc.getTabName();
    sc.getTabName1();
    sc.onUserChange();
    sc.onProfileChange();
  //  system.assert(sc.select_LicType==select_Lictype);
        
        
  
       // page_access__c pc1 = new page_access__c(name='package');
       // insert pc1;
       // ID profile= [Select Id from Profile Where Profile.Name =: 'System Administrator'].ID;
      //  page_access__c pc = new page_access__c(name ='profile');
      //  insert pc;
        
/*    string data = 'check';
    string data1 = 'test';
        try{
        if(data == 'check')
        {
            page_access__c paa = new  page_access__c();
             LMA_Audit__c lma = new LMA_Audit__c(
                   License_Key__c = 'keytesting',
                          License_Type__c = 'IL',
                          Expire_Date__c = date.today() ,
                          User_ID__c = UserInfo.getUserId(),
                          Contact__c = '01',
                          Install_Date__c = date.today(),
                          No_of_Seats__c = 5,
                          Package_Version__c = 'v4.1',
                          Subscriber_Org_Id__c = UserInfo.getOrganizationId(),
                          App_Name__c = 'ConfidentG',
                          Status__c = 'Inactive');
                  insert lma;
            if(data1 == 'test')
            {
                data = 'check ok';                 
            }
            else
            {
                data1 = 'test ok';
                data = null;
            }
        }
        if(data1 == 'test')
        {
                 
        }
        }catch(Exception e){system.debug(e.getMessage());}
        */
    sc.test ();        
  
    }          

}